# Generated by Django 5.2.8 on 2025-11-27 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="todo",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="todo",
            name="resolved",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name="todo",
            index=models.Index(
                fields=["due_date"], name="todo_todo_due_dat_4529b3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="todo",
            index=models.Index(
                fields=["resolved"], name="todo_todo_resolve_7bd82a_idx"
            ),
        ),
    ]
